### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by axlekb** [slim-template/slim-rails#100]
Current gemspec:
```
  gem.add_development_dependency 'actionmailer', ['>= 3.1', '< 5.0']
  gem.add_runtime_dependency 'actionpack', ['>= 3.1', '< 5.0']
  gem.add_runtime_dependency 'railties',   ['>= 3.1', '< 5.0']
```

**Comment by vyorkin** [comment]
Btw I've just tried to relax dependencies and it seems to work, but I'm not aware of any side-effects it may cause

**Comment by axlekb** [comment]
@vyorkin want to create a PR with those changes?

**Comment by vyorkin** [comment]
@axlekb done, but I'm still not sure if everything is ok, tests are green btw

**Comment by Salzig** [comment]
#112 relaxes the dependencies.

**Comment by Salzig** [comment]
feel free to test slim-rails 3.1.0
