### ISSUE TITLE
How to customise SLIM templates inside a Rails 4 project

### ISSUE THREAD

**Issue by danlaffan** [slim-template/slim-rails#131]
I want to have custom view generator templates so that I can use rails g scaffold, and have SLIM files which are pre-baked with Bootstrap tags, etc. 

In my Rails 4 project, what directory structure should I use when generating customised html.slim view generator templates?

**Comment by zavan** [comment]
http://daniel.fone.net.nz/blog/2014/02/01/customising-scaffold-views-in-ruby-on-rails/

Just change `lib/templates/erb` to `lib/templates/slim`.

**Comment by januszm** [comment]
@danlaffan does @zavan solution help?

**Comment by danlaffan** [comment]
I will check this out presently...

**Comment by danlaffan** [comment]
It worked!  These are the files that I created:

    lib/templates/slim/scaffold/edit.html.slim
    lib/templates/slim/scaffold/index.html.slim
    lib/templates/slim/scaffold/new.html.slim
    lib/templates/slim/scaffold/show.html.slim
    lib/templates/slim/scaffold/_form.html.slim

I didn't seem to need to attach .erb at the end of the files, even though they contained some ERB.

Thanks @zavan for your help.
