### ISSUE TITLE
3.1.2 tagged but not on RubyGems

### ISSUE THREAD

**Issue by zavan** [slim-template/slim-rails#138]
It seems that version [3.1.2 is tagged on git](https://github.com/slim-template/slim-rails/releases/tag/v3.1.2), but not released on [RubyGems](https://rubygems.org/gems/slim-rails).

**Comment by zavan** [comment]
Related #128

**Comment by januszm** [comment]
It'll be released shortly.

**Comment by januszm** [comment]
@zavan 3.1.2 released to Rubygems
