### ISSUE TITLE
Slim::Parser::SyntaxError - "Unknown Line Indicator" on an .erb File with 3.1.2

### ISSUE THREAD

**Issue by noahsettersten** [slim-template/slim-rails#146]
# Slim::Parser::SyntaxError in .erb file with slim-rails 3.1.2

**Versions**:
- Rails 5.0.2
- Sprockets 3.7.1
- Slim 3.0.7
- slim-rails 3.1.2

**Description**:
Upgrading to slim-rails@3.1.2 suddenly gives odd errors within .html.erb template files for us. With the only change being an update from slim-rails@3.1.1 to 3.1.2, Slim::Parser::SyntaxErrors are now occurring within a number of our ERB templates. It appears that Slim is attempting to parse these files and having issues with inline scripts or styles. I've included the log for an error that occurs within an inline <script> tag in our 500.html.erb file. It's very odd that the Slim parser is even attempting to process these files with their *.erb extension.

This issue appears to be similar to #145, although occurring on included JavaScript content. Since the application this is happening on has a number of locations with inline style or script tags, moving them to external included files isn't an option to workaround this. Issue #144 may be related as well, but these syntax errors are coming up on ERB files in this case.

**Workaround**:
Locking the version of slim-rails to 3.1.1 in the Gemfile eliminates any of these errors from occurring.

**Log**:
```
Slim::Parser::SyntaxError - Unknown line indicator
  500, Line 105, Column 2
    $(document).ready(function(){
    ^
:
  slim (3.0.7) lib/slim/parser.rb:513:in `syntax_error!'
  slim (3.0.7) lib/slim/parser.rb:259:in `unknown_line_indicator'
  slim (3.0.7) lib/slim/parser.rb:250:in `parse_line_indicators'
  slim (3.0.7) lib/slim/parser.rb:192:in `parse_line'
  slim (3.0.7) lib/slim/parser.rb:95:in `call'
  temple (0.7.7) lib/temple/engine.rb:50:in `block in call'
  temple (0.7.7) lib/temple/engine.rb:50:in `call'
  temple (0.7.7) lib/temple/mixins/template.rb:10:in `compile'
  temple (0.7.7) lib/temple/templates/tilt.rb:30:in `prepare'
  tilt (2.0.7) lib/tilt/template.rb:99:in `initialize'
  slim-rails (3.1.2) lib/slim-rails/register_engine.rb:6:in `call'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.7.1) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.7.1) lib/sprockets/base.rb:73:in `find_all_linked_assets'
  sprockets (3.7.1) lib/sprockets/manifest.rb:134:in `block in find'
  sprockets (3.7.1) lib/sprockets/manifest.rb:133:in `find'
```

**Comment by jtomaszewski** [comment]
Very similar error here: https://github.com/galetahub/ckeditor/issues/734 

Seems like slim tries to compile all html files even when it shouldnt?

**Comment by eric-simonton-sama** [comment]
My team ran into this problem as well, and it makes this version of `slim-rails` completely unusable for us, because we have many `.html` files.

More info: you can get around the error by indenting the contents of the `html` file and adding `/` as the first line (i.e. comment out the whole file if it actually was slim). Then once the page is serving you can revert all the HTML files and they will continue to work. This is in a development environment where we do not precompile assets.

**Comment by januszm** [comment]
@noahsettersten @eric-simonton-sama we released version 3.1.3, please upgrade and re-test

**Comment by eric-simonton-sama** [comment]
Looks good from my first test. I'll let you know if it crops up again. Thanks!

**Comment by noahsettersten** [comment]
Will do. Thanks for resolving this!
