### ISSUE TITLE
Line breaks and `Slim::Parser::SyntaxError`: how to fix it?

### ISSUE THREAD

**Issue by ghost** [slim-template/slim-rails#147]
Hi everyone,

I'm actually facing a weird problem on a ROR app, using slim-rails. When I call a helper (a quite huge one) in my view, I want to break the lines which are too long, but if I do so I've got an error like `Slim::Parser::SyntaxError Expected tag`... This seems related to line breaks, but I can't figure out how to fix this :cry: 

Here is a bit of my code, if it can help:
```
= table_builder @collection,
  [
    TableBuilderHelper::Column.new(
      key: :name,
      attribute: 'name'
    ),
    TableBuilderHelper::Column.new(
      ...
    ),
    ...
  ]
```

Thx in advance for your help!

**Comment by januszm** [comment]
@soykje we released version 3.1.3, please upgrade and re-test
