### ISSUE TITLE
Please release 3.1.3 gem

### ISSUE THREAD

**Issue by amatsuda** [slim-template/slim-rails#149]
Current newest stable 3.1.2 gem seems broken when combined with sprockets 3.x. It tries to parse non-slim file via Slim, then causes `Slim::Parser::SyntaxError` on my app.
It's been fixed in master via #142, so I appreciate if you could just package current master and push it as 3.1.3 gem. 🙏 
I suppose some recently reported issues such as #140, #144, #145, #146, #147 could be hitting the same problem, and so you can close them all with the new gem release.

**Comment by januszm** [comment]
@amatsuda 3.1.3 released

**Comment by amatsuda** [comment]
@januszm Wow, so quick! Thank you! 🎉
