### ISSUE TITLE
Update templates to use 'form_with'

### ISSUE THREAD

**Issue by andibachmann** [slim-template/slim-rails#160]
As pointed out in the original [DHH's proposal](https://github.com/rails/rails/issues/25197) `form_tag` and `from_for` will superseeded by `form_with` (see [API documentation](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with) ).

I suggest to update the relevant SLIM templates.

**Comment by januszm** [comment]
Resolved with https://github.com/slim-template/slim-rails/pull/178
