### ISSUE TITLE
Issue with finding template in rails 6 engine

### ISSUE THREAD

**Issue by xiazek** [slim-template/slim-rails#162]
I can't make it working inside freshly generated Rails 6 engine. 

Error says:
`No template for interactive request`
`TestingController#test1 is missing a template for request formats: text/html`

I have successfully used slim-rails in many projects with rails 5.x

**Comment by januszm** [comment]
Support for the "0" release of Rails 6 has not been added yet

**Comment by vizo** [comment]
Is there any quick solution for this?

**Comment by christopherfujino** [comment]
Is support for Rails 6 being tracked?

**Comment by januszm** [comment]
@xiazek  could you give me more details about the problem? I just generated a fresh Rails 6 app and slim-rails works just fine.

Ideally, please share the link to the Git repository of the app where you experience a problem with slim-rails and add some information about the context.

**Comment by januszm** [comment]
@xiazek it seems that your issue was related to the "indirect" dependency of slim-rails, gem temple.  It was updated (now to 0.8.2 https://rubygems.org/gems/temple) and supports Rails 6.

I'll close this issue and suggest to `bundle update` your projects to start using the latest `temple`.

**Comment by xiazek** [comment]
Thanks @januszm That fixed the problem !
