### ISSUE TITLE
Syntax error, unexpected keyword_rescue, expecting keyword_end

### ISSUE THREAD

**Issue by nhunguyen15998** [slim-template/slim-rails#182]
SyntaxError: /usr/local/bundle/gems/slim-rails-3.5.0/lib/slim-rails.rb:29: syntax error, unexpected keyword_rescue, expecting keyword_end

**Comment by januszm** [comment]
Interesting, I see it's closed, but just curious, did you use Ruby version older than 2.5?

**Comment by nhunguyen15998** [comment]
Yes, this error appeared in redmine 3.4.12, and i don't know how to fix it...

**Comment by januszm** [comment]
What version of Ruby are you using?

**Comment by nhunguyen15998** [comment]
I use Ruby 2.4.9

**Comment by egor-khanko** [comment]
Same here for me, Ruby 2.4.1

**Comment by januszm** [comment]
@nhunguyen15998  @egor-khanko  I hate to say it, but in this case I recommend that you update Ruby in your projects to at least 2.5, 2.6 or 2.7 if you can't jump to 3. Future versions of this gem will probably only include updates for the new Rails 7+. Rails 6.0 already requires Ruby 2.5 or later.
If you cannot use the newer version of Ruby for some reason, please lock the slim-rails version to:

```
gem 'slim-rails', '< 3.4.0'
```

**Comment by egor-khanko** [comment]
@januszm Should I create PR with required Ruby version bump?)

**Comment by januszm** [comment]
@egor-khanko  I'll make this gem compatible with older Rubies again in https://github.com/slim-template/slim-rails/pull/183 , but still, why are your projects on Ruby 2.4 ? Upgrading, at least to 2.5 or 2.6 should be trivial.
