### ISSUE TITLE
Incompatible with Rails 8

### ISSUE THREAD

**Issue by cvshepherd** [slim-template/slim-rails#199]
Rails 8 has dropped support for Sprockets in favor of Propshaft, leading to a multitude of app breaking errors when trying to use this gem.

**Comment by januszm** [comment]
Could you share exact error messages here?

To be honest, I've just started a fresh Rails 8 application with slim-rails and I didn't see any issues with most basic setup and views:

```sh
> rails g scaffold Post title body
      invoke  active_record
      create    db/migrate/20241116170917_create_posts.rb
      create    app/models/post.rb
      invoke  resource_route
       route    resources :posts
      invoke  scaffold_controller
      create    app/controllers/posts_controller.rb
      invoke    slim
      create      app/views/posts
      create      app/views/posts/index.html.slim
      create      app/views/posts/edit.html.slim
      create      app/views/posts/show.html.slim
      create      app/views/posts/new.html.slim
      create      app/views/posts/_form.html.slim
      create      app/views/posts/_post.html.slim
      invoke    resource_route
      invoke    helper
      create      app/helpers/posts_helper.rb
❯ bin/rails db:migrate
== 20241116170917 CreatePosts: migrating ======================================
-- create_table(:posts)
   -> 0.0010s
== 20241116170917 CreatePosts: migrated (0.0010s) =============================

> bin/dev
# GET localhost:3000/posts
Started GET "/posts" for ::1 at 2024-11-16
Processing by PostsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering posts/index.html.slim within layouts/application
  Post Load (1.1ms)  SELECT "posts".* FROM "posts" /*action='index',application='New8',controller='posts'*/
  ↳ app/views/posts/index.html.slim:6
  Rendered posts/index.html.slim within layouts/application (Duration: 11.4ms | GC: 1.0ms)
  Rendered layout layouts/application.html.erb (Duration: 12.2ms | GC: 1.0ms)
```

**Comment by unRARed** [comment]
Dunno if related, but I'm getting this with Rails 8 when trying to make a logout button for the new auth pattern:

<img width="491" alt="Screenshot 2024-12-26 at 10 21 21 AM" src="https://github.com/user-attachments/assets/5d927742-b18c-4c95-9dd2-1636a19a55cd" />

<img width="408" alt="Screenshot 2024-12-26 at 10 22 01 AM" src="https://github.com/user-attachments/assets/590b4a6e-c55e-4715-b780-330f5eedc2d2" />

**Comment by unRARed** [comment]
So almost certainly related, it looks like `slim-rails` is not compatible (yet) with the new Rails 8.0.1 auth generator either (`bin/rails generate authentication`)

<img width="992" alt="Screenshot 2024-12-26 at 10 39 44 AM" src="https://github.com/user-attachments/assets/0adf7eec-b9e2-480d-8193-58a2d54b0ed9" />

Running again after replacing with just `slim` (probably same as if no slim in Gemfile) it actually creates the session views:

<img width="487" alt="Screenshot 2024-12-26 at 10 40 51 AM" src="https://github.com/user-attachments/assets/d622c2fa-d638-4e75-a78c-2fd7e7331db7" />

**Comment by taketo1113** [comment]
The current version of `slim-rails` (v3.6.3) does not yet support the authentication generator.
It seems that adding an `AuthenticationGenerator`, similar to how it's done with `rspec-rails`, could enable support for it.
https://github.com/rspec/rspec-rails/pull/2811

Other than the authentication generator, the features seem to be working fine with Rails 8.0.
In the following Pull Request, the CI matrix was updated for Rails 8.0, and the tests are passing:

- #200

---

@unRARed  The error mentioned in the comment (https://github.com/slim-template/slim-rails/issues/199#issuecomment-2563007970) below seems to be a syntax error with `button_to`, so it doesn't appear to be related to the slim-rails gem.

I believe the error can be fixed by making the following adjustment:
```diff
-                = button_to("Log out", session_path,
+                = button_to(session_path,
                   method: :delete,
                   data: { turbo_methid: :delete },
                   class: 'test-blue-500' \
-                )
+                ) do
                   span Log out
```

**Comment by taketo1113** [comment]
I also created a PR to support the authentication generator.

- #201

**Comment by januszm** [comment]
Thanks to @taketo1113  , I've just released new gem version with support for authentication generator.
