### ISSUE TITLE
Allow Pretty format for develpment mode and deeper Slim configuration

### ISSUE THREAD

**Issue by hilios** [slim-template/slim-rails#30]
It would be nice to have this configurations bundled into the gem, won't you think?

``` ruby
Slim::Engine.set_default_options pretty: Rails.env.development?, sort_attrs: Rails.env.development?
```

And also have the config option inside rails application itself, so we could allow users to setup Slim completely without monkey-patching.

``` ruby
module Radness
  class Application < Rails::Application
    # ...
    config.slim_template.pretty = true
    config.slim_template.sort_attrs = true
    # or block style
    config.slim_template do
      pretty = true
      sort_attrs = true
    end
  end
end
```

What you think about it?

**Comment by Fedcomp** [comment]
I just ran into this. It would be nice to have application.rb/environments config so it would feel well integrated into rails.

> The second proposal however is not an option since Slim/Temple brings its own configuration framework independant of rails.

It doesn't have to inherit rails configuration, it may have simple class which will proxy all configuration calls to slim engine.

In pseudocode:
```ruby
class SlimRailsConfigProxy
  def method_missing(method, args)
    if Slim::Engine.options.respond_to?(method)
      Slim::Engine.options.send(method, args)
    else
      raise ArgumentError, "Slim does not have option #{method}"
    end
  end
end
```

@minad may you reconsider your decision? would you accept PR of such functionality?

**Comment by januszm** [comment]
@Fedcomp  sounds good. I'm the current maintainer of this gem, let's work on a new PR for this functionality.

**Comment by Fedcomp** [comment]
Okay thanks! i'll try to make a PR this or next weekend.

**Comment by Fedcomp** [comment]
@januszm sorry. Unfornately when i found time to work on it, i ran into incompatibility with rails 3, and left no time and willing to resolve it. And i'll probably stop.
