### ISSUE TITLE
why my form_tag doesn't work?

### ISSUE THREAD

**Issue by tsaomichael** [slim-template/slim-rails#62]
I use slim-rails 2.1.5,but i have one question.My form_tag doesn't work.But form submit and reload page .The url show authenticity_token and params .Can you help me?

my example:

= form_tag export_probability_settings_path, multipart:true do

environment ruby 2.1 rails 4.1.5

**Comment by romenigld** [comment]
I'm facing the same problem what was your final form tag?
I'm trying to do this
```
li
        = form_tag search_posts_path(@post), method: :get, class: "form-inline" do
          = label_tag "search", "Search", class: "sr-only"
          = text_field_tag "search", params[:search], class: "form-control"
          = submit_tag "Search", class: "btn btn-default"
```

And I'm getting this error on RSpec:
```
Failure/Error: fill_in "Search", with: "tag:iteration_1"

     Capybara::ElementNotFound:
       Unable to find field "Search"
```
