### ISSUE TITLE
Update slim include partials under development

### ISSUE THREAD

**Issue by lephyrius** [slim-template/slim-rails#63]
This is the original issue:
https://github.com/slim-template/slim/issues/558

Basically I want Slim include partials to update because it would ease development. I think they look soo much nicer than rails partials to use. I know that this cannot be used everywhere like when u need dynamic partial names.

**Comment by januszm** [comment]
This issue is so old, I don't think this is relevant anymore. If you'd still like to implement this, please create a PR.
