### ISSUE TITLE
Rails 4.2 - actionamailer

### ISSUE THREAD

**Issue by rogermingorance** [slim-template/slim-rails#79]
We can not update to rails 4.2 becuase of the dependency on 'actionmailer' gem:
$ bundle update rails
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "actionmailer":
In Gemfile:
  slim-rails (>= 0) ruby depends on
    actionmailer (< 4.2, >= 3.0) ruby

  rails (= 4.2.0) ruby depends on
    actionmailer (4.2.0)

**Comment by minad** [comment]
should be fixed in newest version
