### ISSUE TITLE
Using Slim Rails inside Engine

### ISSUE THREAD

**Issue by ziyan-junaideen** [slim-template/slim-rails#86]
I am building a Rails engine. I would like to use Slim Rails in the engine. When I do generate controller etc the views are in ERB. When I tried to `require 'slim-rails'` in `engine.rb` file it says there is no such required.

Is it possible to use Slim Rails in an engine. If so is this a bug or am I doing it wrong. As I remember if I just `bundle install` slim rails in a Rails app it just works.

Thanks in advance.

**Comment by kayluhb** [comment]
:+1:

**Comment by istana** [comment]
I think this can be closed, in the Rails engine you must require gems in `lib/my_engine.rb`. I just tried and and it works.

**Comment by donv** [comment]
I had to expand on this fix to get things working in my engine.  I had to only require runtime dependencies and account for gems with initializers in subdirectories.

In `lib/my_engine.rb`:

```ruby
Gem.loaded_specs['datek-dlc-api'].dependencies.select { |d| d.type == :runtime }.each do |d|
  require d.name
rescue LoadError
  require d.name.gsub('-', '/')
end
```
