### ISSUE TITLE
error: slim [not found]

### ISSUE THREAD

**Issue by cpg** [slim-template/slim-rails#91]
I was just running a generator running rails 4.2.1 and I saw this error where the slim templates do not get generated
```
bundle exec rails g scaffold RegressionRun regression:references ...
...
      invoke  scaffold_controller
   identical    app/controllers/regression_runs_controller.rb
       error    slim [not found]
      invoke    rspec
...
```

And slim works well otherwise in the app for a long time. I tried to run rails bare and also with bundle exec rails generate ....

Using slim 3.0.4.

I could not find where this comes from by searching around. Any ideas what could be happening here?

**Comment by gerep** [comment]
Can you share your Gemfile? Are you sure that 'slim-rails' is installed?

**Comment by cpg** [comment]
duh. my bad. sorry for the derpiness. i only had slim and not slim-rails.

**Comment by gerep** [comment]
It happens =)

Be aware that starting from the version `0.2.0` you don't need to include
```ruby
gem slim
```
only
```ruby
gem slim-rails
```

**Comment by manto0530** [comment]
i have added gem 'slim-rails' and its been install to why I cont able to get it

**Comment by manto0530** [comment]
when i use scaffold i can able to get the slim data but when I use nested_scaffold i cont able to generate the slim file
