### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by thomasklemm** [slim-template/slim-rails#94]
Hi, 3dd168b51e3cf4ebb09fc7081c42df799267f090 is still unreleased but already several months in master. Could you on occasion push a new release to Rubygems?

**Comment by dogweather** [comment]
:+1:

**Comment by januszm** [comment]
Guys who have access to rubygems to release new versions? ( @Salzig @minad )

**Comment by Salzig** [comment]
only @leogalmeida has. Mailed him twice, no response so far.

**Comment by leogalmeida** [comment]
Really sorry, guys. I was offline this weekend. I'll add Ben to rubygems as soon as possible

Leonardo Almeida
