### ISSUE TITLE
Is ActionMailer really necessary?

### ISSUE THREAD

**Issue by neves** [slim-template/slim-rails#97]
https://github.com/slim-template/slim-rails/blob/master/slim-rails.gemspec#L30

**Comment by deepj** [comment]
Here is PR (#93) removing that. Unfortunately, no maintainer isn't interesting in that :(

**Comment by januszm** [comment]
Seems to be necessary only as a devdependency (we've already updated the gemspec). In tests we have a test for mailer generator. This tests ```Rails::Generators::MailerGenerator```

defined in ActionMailer in

```actionmailer/lib/rails/generators/mailer/mailer_generator.rb```
