### ISSUE TITLE
Slim-rails doesn't work with Rails 4.2.x

### ISSUE THREAD

**Issue by facatalan** [slim-template/slim-rails#99]
Hello, slim-rails seems not compatible with rails 4.2.x...
```
$ bundle update rails
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    slim-rails (>= 0) ruby depends on
      actionpack (< 4.2, >= 3.0) ruby

    rails (= 4.2) ruby depends on
      actionpack (4.2.0)
```

**Comment by axlekb** [comment]
It's likely you need to update `slim-rails` as well. When you `bundle update rails`, it tries to _only_ update `rails`.  Try `bundle update rails slim-rails` which will allow `slim-rails` to update as well.
